### ISSUE TITLE
Dragging a block to the last position in the row doesn't show the ghost element correctly

### ISSUE THREAD

**Issue by TheFoot** [TheFoot/vue-grid-designer#8]
When you drag a block from one row to the next, into the last position on the row, the ghost element shows on the next "line" (correct row).

**Expected behavior**
The ghost element should appear as the last block in the row.

**Actual behavior**
The toolbar element (even though it is filtered out of the draggable list) is causing SortableJS to get confused, because it is a child element of the row.

Could file a bug with SortableJS.. 🤔  Would rather fix the toolbar placement though.

Main issue is making sure we don't resort to DOM hacks (not very _Vuey_), and also being able to pass current row/block scope vars to the toolbar action buttons.
 
@rorysmorris suggested to move the element outside the row, and position it using a style binding for x/y coords. On row hover - store the current row/block as component data, as well as x/y coords.

**Comment by sharq88** [comment]
Traced it down... It was caused by a bug in Sortable.JS last item position calculation. It can be worked around by moving the `Row toolbar` to the first position in the DOM of the row.
```
<div class='vgd__row'>
  <div class='no-drag'>...</div>
  <div class='vgd__block'>...</div>
  <div class='vgd__block'>...</div>
  ...
</div>
```
